apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: athlete
      namespace: theassembly-apps
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 768Mi
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: admin
      namespace: theassembly-apps
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 768Mi
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: mcp-playwright
      namespace: theassembly-mcp
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: mcp-pyright
      namespace: theassembly-mcp
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
